Functional tests
RachiLam/codenames-duet pull request #11
Opened 2021-02-17 00:44 UTC by rachidlamouri

Adding functional tests for these features
- random words
- turn counters
- reset buttons

Additional project tasks were added for these features
- card colors
- admin mode

2021-04-21 03:59 UTC, mollyhenderson requested changes
Request the changes! 🦑

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/hooks.js
> +  return new Promise((resolve) => setTimeout(resolve, 2000));
:wave: why is this 2sec delay here? (Maybe we need a comment?)

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/hooks.js
> +global.Promise = require('bluebird');
Don't override the global Promise plz

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/steps.js
> +      pattern: '^[A-Z][A-Z ]*[A-Z]$',
Why is there a space? Also, this regex implies a min length of 2

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/steps.js
> +      expect(await topHalf.word()).to.equal(await bottomHalf.word());
Should probably have some info in the error message.

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/steps.js
> +  await resetButton.element.click();
We shouldn't be accessing `element` here.

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/features/turnCounters.feature
> +  Scenario Outline: All turns taken
Looks like this *might* not be running. Should this just be a `Scenario`?

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/features/turnCounters.feature
> +      | playerId | turnType   | remainingCount | indicesClause      | indexClause |
`remainingCount` is unused

2021-04-21 03:59 UTC, mollyhenderson commented on tests/functional/support/steps.js
> +  const cardIndicesText = indicesClause.replace(/on cards /, '');
Looks like this line might not be doing anything (`indicesClause` shouldn't contain `on cards` at this point)

2022-02-07 23:10 UTC, rachidlamouri commented
This is a year old, and this project is too far into my backlog for this to be updated any time soon. I'll reopen if I ever get back to it.

2022-02-07 23:10 UTC, closed without merging